[package]
name = "shira"
version = "1.1.0"
authors = ["Lucas De Angelis <deangelis.lucas@outlook.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.3"